#ifndef _BIN2C_HEADER_6057_6BB8_2D23_78A8_
#define _BIN2C_HEADER_6057_6BB8_2D23_78A8_

/* generated by bin2c from file copystub.bin */
#define COPYSTUB_BIN_SIZ 320
extern const unsigned char copystub_bin_dat[];

#endif // _BIN2C_HEADER_6057_6BB8_2D23_78A8_
