name: Build Ftx Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libftdi1-dev

      - name: Create build directory and build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ftx
          path: build/ftx

      - name: Upload executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${GITHUB_REF##*/}/assets
          asset_path: build/ftx
          asset_name: ftx
          asset_content_type: application/octet-stream
        if: github.ref_type == 'tag'
